In [1]:
!pip install numpy
!pip install scipy
!pip install sympy
!pip install matplotlib
!pip install mpmath

Defaulting to user installation because normal site-packages is not writeable

[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: pip install --upgrade pip
Defaulting to user installation because normal site-packages is not writeable

[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: pip install --upgrade pip
Defaulting to user installation because normal site-packages is not writeable

[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: pip install --upgrade pip
Defaulting to user installation because normal site-packages is not writeable

[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: pip install --upgrade pip
Defaulting to user installation because normal site-packages is not writeable

[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: pip install --upgrade pip


In [12]:
import sympy
x,y,s,t=sympy.var('x,y,s,t')
a,n = sympy.symbols('a,n',real=True,positive=True)

def L(f):
    return sympy.laplace_transform(f,t,s,noconds=True)

def invL(F):
    return sympy.inverse_laplace_transform(F,s,t)

f=sympy.exp(-a*t)*t**n
F=L(f)

g=f.diff(t)

h=sympy.cos(a*t)
H=L(h)

i=g.diff(t)

j=h.diff(t)

display(F)
display(invL(F))

display(L(g))

display(H)
display(invL(H))

display(L(i))

display(L(j))

(a + s)**(-n - 1)*gamma(n + 1)

t**n*exp(-a*t)*Heaviside(t)

-a*(a + s)**(-n - 1)*gamma(n + 1) + n*gamma(n)/(a + s)**n

s/(a**2 + s**2)

cos(a*t)*Heaviside(t)

a**2*(a + s)**(-n - 1)*gamma(n + 1) - 2*a*n*gamma(n)/(a + s)**n + n**2*(a + s)**(2 - n)*gamma(n - 1)/(a + s) - n*(a + s)**(2 - n)*gamma(n - 1)/(a + s)

-a**2/(a**2 + s**2)

In [19]:
def prime(s:int,e:int):
    l=[]
    m=[]
    for i in range(s,e+1):
    
        for j in range(1,i):
            if i%j==False:
                l.append(j)
        if l==[1]:
            m.append(i)
        l=[]
    print(m)
    return None

prime(1,100)


[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


In [22]:
import sympy
x,y,s,t=sympy.var('x,y,s,t')
a,n = sympy.symbols('a,n',real=True,positive=True)

def L(f):
    '''
    Laplace_transform
    '''
    return sympy.laplace_transform(f,t,s,noconds=True)

help(L)

Help on function L in module __main__:

L(f)
    Laplace_transform



In [57]:
s='République français'

for i in s:
    print(i,end='')
print()
for i,a in enumerate(s):
    if i%2==False:
        s=s.replace(s[i],'0')
print(s)


République français
0é000l0q0e0f000ç000


In [46]:
import numpy as np
str1=input()
str2=input()
fibonacci=[]
for i in range(40):
    fibonacci+=[int( 1/(5**0.5)*(((1+5**0.5)/2)**i-((1-5**0.5)/2)**i))]
c=[int(i) for i in str1.split()]
d=[int(i) for i in str2.split()]
for index, value in enumerate (c):
    if value%2==0:
        c[index]=1
for index, value in enumerate (d):
    if fibonacci.count(d[index])>0:
        d[index]=-1        
x=np.array(c).reshape(3,5)
y=np.array(d).reshape(5,3)

print(x)
print(y)
print(np.dot(x,y))

[[ 1  1  3  1  5]
 [ 1  7  1  9  1]
 [11  1 13  1 15]]
[[-1 -1 -1]
 [ 4  6 -1]
 [10 12 14]
 [16 18 20]
 [22 24 26]]
[[159 179 190]
 [203 239 212]
 [469 529 580]]


In [ ]:
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
2 0 2 4 6 8 10 12 14 16 18 20 22 24 26

In [62]:
'a'.join('fuck')
'fuck you'.split(' ')

['fuck', 'you']